# Generated by Django 4.1.2 on 2022-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="text",
        ),
        migrations.AddField(
            model_name="test",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="test",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="phone",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="qualification",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="sex",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
