# Generated by Django 4.1.2 on 2022-10-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0002_remove_test_text_test_address_test_age_test_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "Test", "verbose_name_plural": "Testy"},
        ),
        migrations.AlterField(
            model_name="test",
            name="name",
            field=models.CharField(
                help_text="This is  the name os user", max_length=100, null=True
            ),
        ),
    ]
